### ISSUE TITLE
Value is truncated if contains a '//'

### ISSUE THREAD

**Issue by seatedscribe** [NatWeiss/ValTree#7]
Hello there 😃 
When parsing the key-value text file, in ValTree::parse() a check is performed to skip comments [here](https://github.com/NatWeiss/ValTree/blob/7895a7d113074818c29cd96f1cc4cc3de6e4b6b6/ValTree.cpp#L510)
While this is not documented, it prevents any URL to be correctly retrieved as the result would be just a truncated 'http:'

I suggest to remove this check as it is not in the scope of the service. If I will have time I could submit a PR

**Comment by NatWeiss** [comment]
Thanks for finding this issue and submitting a pull request. I've merged it. Much appreciated.

**Comment by seatedscribe** [comment]
👍
